blank_issues_enabled: false
contact_links:
  - name: Repository moved to Kaleidos Ventures organization
    url: https://github.com/kaleidos-ventures/taiga-resources/issues/new/choose
    about: We've moved our repositories to a new organization. Please, follow Taiga development from the new one.
